project_id = "xcnfyawyoahlbhwfkyku"

[functions.createTestAccount]
verify_jwt = false

[functions.publicCaptureContact]
verify_jwt = false

[functions.lookupContactByToken]
verify_jwt = false

[functions.deleteContactByToken]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.sms-status-webhook]
verify_jwt = false

[functions.createCustomerAccount]
verify_jwt = false

[functions.sendWelcomeEmail]
verify_jwt = false

[functions.google-oauth-callback]
verify_jwt = false

[functions.fetch-google-reviews]
verify_jwt = false

[functions.auto-reply-cron]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.send-merchant-onboarding]
verify_jwt = false

[functions.geocode-address]
verify_jwt = false

[functions.birthday-cron]
verify_jwt = false

[functions.password-setup-redirect]
verify_jwt = false

[functions.send-app-verification-email]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.on-new-app-message]
verify_jwt = false

[functions.send-three-day-email]
verify_jwt = false
